sudo: required
services:
  - docker
  
language: generic

before_install:
  - docker build -t firnaa5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true firnaa5/docker-react npm run test -- --coverage