sudo: required
services:
  - docker
  
language: generic

before_install:
  - docker build -t firnaa5/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true firnaa5/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeantalsk"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"